### PR TITLE
Update Joda-Convert and Joda-Money versions

### PR DESCRIPTION
**Pull request by johnspade**
- joda-convert -> 2.2.1
- joda-money -> 1.0.1

### CODE REVIEW

**Comment by drbild** [comment]
Thanks!

Looks like the Travis CI config needs to be updated to JDK 9 for the CI to pass.  Feel free to add that to this PR, if you get a chance before I do.

**Comment by johnspade** [comment]
Ok, I fixed Travis builds.

**Review by drbild — APPROVED** [review]
LGTM.  Thanks!

**Comment by johnspade** [comment]
Thank you for this library!

**Pull request merged**
